baseURL = "http://abcx.org/"
googleAnalytics = "UA-123-45"
languageCode = "en-us"
theme = "bloggeri"
title = "Grynn's template"
[[menu.main]]
name = "Office"
parent = "Women"
url = "Office"
weight = 2
[[menu.main]]
name = "Sports"
parent = "Women"
url = "Sports"
weight = 1
[[menu.main]]
name = "Office"
parent = "Men"
url = "Office"
weight = 2
[[menu.main]]
name = "Kids"
url = "/Kids"
weight = 3
[[menu.main]]
name = "Women"
url = "/Women"
weight = 2
[[menu.main]]
name = "Sports"
parent = "Men"
url = "Sports"
weight = 1
[[menu.main]]
name = "Men"
url = "/Men"
weight = 1
[[menu.social]]
name = "YouTube"
pre = "<i class='fab fa-youtube'></i>"
url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
weight = 2
[[menu.social]]
name = "Twitter"
pre = "<i class='fab fa-twitter'></i>"
url = "https://twitter.com/pakstech"
weight = 1
[[menu.social]]
name = "GitHub"
pre = "<i class='fab fa-github'></i>"
url = "https://github.com/pakstech"
weight = 3
[params]
description = "My site description"
